name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Path:
    description: The path to the code to test.
    required: true
    default: ${{ github.workspace }}
  Settings:
    description: The type of tests to run. Can be either 'Module', 'SourceCode' or 'Custom'.
    required: false
    default: 'Custom'
  SettingsPath:
    description: The path to the settings file.
    required: false
    default: ${{ github.workspace }}/.github/linters/.powershell-psscriptanalyzer.psd1

outputs:
  passed:
    description: If the tests passed.
    value: ${{ steps.test.outputs.Passed }}

runs:
  using: composite
  steps:
    - name: Get test paths
      uses: PSModule/Github-Script@v1
      id: paths
      env:
        GITHUB_ACTION_INVOKE_SCRIPTANALYZER_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INVOKE_SCRIPTANALYZER_INPUT_Settings: ${{ inputs.Settings }}
        GITHUB_ACTION_INVOKE_SCRIPTANALYZER_INPUT_SettingsPath: ${{ inputs.SettingsPath }}
      with:
        Script: ${{ github.action_path }}/scripts/main.ps1

    - name: Invoke-Pester
      uses: PSModule/Invoke-Pester@fix
      id: test
      with:
        TestResult_TestSuiteName: PSScriptAnalyzer
        Path: ${{ fromJson(steps.paths.outputs.result).TestPath }}
        Run_Path: ${{ inputs.Path }}
