name: Invoke-ScriptAnalyzer (by PSModule)
description: Runs PSScriptAnalyzer on the code.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Path:
    description: The path to the code to test.
    required: false
    default: '.'
  Settings:
    description: The type of tests to run. Can be either 'Module', 'SourceCode' or 'Custom'.
    required: false
    default: Custom
  SettingsFilePath:
    description: If 'Custom' is selected, the path to the settings file.
    required: false
    default: ${{ github.workspace }}/.github/linters/.powershell-psscriptanalyzer.psd1
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Get-TestPaths
      uses: PSModule/Github-Script@v1
      id: paths
      env:
        PSMODULE_INVOKE_SCRIPTANALYZER_INPUT_Path: ${{ inputs.Path }}
        PSMODULE_INVOKE_SCRIPTANALYZER_INPUT_Settings: ${{ inputs.Settings }}
        PSMODULE_INVOKE_SCRIPTANALYZER_INPUT_SettingsFilePath: ${{ inputs.SettingsFilePath }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        WorkingDirectory: ${{ inputs.WorkingDirectory }}
        Script: ${{ github.action_path }}/scripts/main.ps1

    - name: Invoke-Pester
      uses: PSModule/Invoke-Pester@v3
      id: test
      env:
        Settings: ${{ fromJson(steps.paths.outputs.result).Settings }}
        SettingsFilePath: ${{ fromJson(steps.paths.outputs.result).SettingsFilePath }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        WorkingDirectory: ${{ inputs.WorkingDirectory }}
        TestResult_TestSuiteName: PSScriptAnalyzer
        Path: ${{ github.action_path }}/scripts/tests/PSScriptAnalyzer
        Run_Path: ${{ fromJson(steps.paths.outputs.result).CodePath }}
