name: Invoke-ScriptAnalyzer (by PSModule)
description: Runs PSScriptAnalyzer on the code.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Path:
    description: The path to the code to test.
    required: true
    default: ${{ github.workspace }}
  Settings:
    description: The type of tests to run. Can be either 'Module', 'SourceCode' or 'Custom'.
    required: false
    default: 'Custom'
  SettingsFilePath:
    description: If 'Custom' is selected, the path to the settings file.
    required: false
    default: ${{ github.workspace }}/.github/linters/.powershell-psscriptanalyzer.psd1

outputs:
  passed:
    description: If the tests passed.
    value: ${{ steps.test.outputs.Passed }}

runs:
  using: composite
  steps:
    - name: Get test paths
      uses: PSModule/Github-Script@v1
      id: paths
      env:
        GITHUB_ACTION_INVOKE_SCRIPTANALYZER_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INVOKE_SCRIPTANALYZER_INPUT_Settings: ${{ inputs.Settings }}
        GITHUB_ACTION_INVOKE_SCRIPTANALYZER_INPUT_SettingsFilePath: ${{ inputs.SettingsFilePath }}
      with:
        Script: ${{ github.action_path }}/scripts/main.ps1

    - name: Invoke-Pester
      uses: PSModule/Invoke-Pester@fix
      id: test
      env:
        Settings: ${{ fromJson(steps.paths.outputs.result).Settings }}
        SettingsFilePath: ${{ fromJson(steps.paths.outputs.result).SettingsFilePath }}
      with:
        TestResult_TestSuiteName: PSScriptAnalyzer
        Path: ${{ github.action_path }}/scripts/tests/PSScriptAnalyzer
        Run_Path: ${{ inputs.Path }}
