name: Action-Test [Src-Default-Custom]

run-name: "Action-Test [Src-Default-Custom] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ActionTestCustom:
    uses: ./.github/workflows/ActionTestWorkflow.yml
    with:
      TestType: Src-Default-Custom
      Path: tests/srcTestRepo/src
      Settings: Custom
      SettingsFilePath: tests/srcTestRepo/tests/Custom.Settings.psd1
