name: Action-Test [outputs]

run-name: "Action-Test [outputs] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ActionTest:
    uses: ./.github/workflows/ActionTestWorkflow.yml
    with:
      TestType: outputs
      Path: tests/outputTestRepo/outputs/modules/PSModuleTest
      Settings: Module
      SettingsFilePath:
