on:
  workflow_call:
    inputs:
      TestType:
        type: string
        required: true
      Path:
        type: string
        required: true
      Settings:
        type: string
        required: false
      SettingsFilePath:
        type: string
        required: false

permissions: {}

jobs:
  ActionTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: '${{ inputs.Path }} - ${{ inputs.TestType }} [${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        id: action-test
        with:
          Path: ${{ inputs.Path }}
          Settings: ${{ inputs.Settings }}
          SettingsFilePath: ${{ inputs.SettingsFilePath }}

      - name: Status
        shell: pwsh
        run: |
          Write-Host "Outcome: ${{ steps.action-test.outcome }}"
          Write-Host "Conclusion: ${{ steps.action-test.conclusion }}"
